#macro C_GRAVITY 0.6
#macro C_MOVE_FRICTION 0.8
#macro C_TERMINAL_VELOCITY 8
#macro C_SLOPE_ATTRACT_RANGE 4
#macro C_ON_HORIZONTAL_FRAMES 6
#macro C_ON_VERTICAL_FRAMES 8
#macro C_ON_WALL_FRICTION 0.3
#macro C_VARIABLE_JUMP_FRICTION 0.6
#macro C_JUMP_REMEMBER_FRAMES 1 << 15 // uses binary counter
#macro C_COLLISION_ONE_WAY_BUFFER 1
#macro C_COLLISION_ONE_WAY_MOVE 2

#macro DEPTH_SYSTEM -16000

#macro VIEW view_camera[0]
#macro VIEW_WIDTH 540
#macro VIEW_HEIGHT 220
#macro GUI_WIDTH  1080
#macro GUI_HEIGHT 1080
#macro ZOOM_MIN 0.1
#macro ZOOM_MAX 4
#macro ZOOM_SPEED 0.1